title: Majuu Journal
description: Your ultimate, community-driven guide to navigating life, work, and opportunities abroad.
theme: jekyll-theme-minimal

# Google Analytics 4 (GA4) Integration
google_analytics: G-KWH9DP3G87
