title: Majuu Journal
description: Your ultimate, community-driven guide to navigating life, work, and opportunities abroad.
theme: jekyll-theme-minimal
baseurl: "/Majuu-Journal"
url: "https://majuu254.github.io"
